version: '3'

services:
  app:
    build: .
    volumes:
      - ..:/app
      - vendor:/app/vendor
      - node_modules:/app/frontend/node_modules
      - yarn_cache:/usr/local/share/.cache/yarn/v1
    extra_hosts:
      localhost: "${DOCKER_HOST_IP}"
    ports:
      - 3000:3000
    command: tail -f /dev/null

volumes:
  vendor:
  node_modules:
  yarn_cache:
