version: '3'

services:
  app:
    build: .
    volumes:
      - ..:/app
      - vendor:/app/vendor
      - frontend:/app/node_modules
    extra_hosts:
      localhost: "${DOCKER_HOST_IP}"
    ports:
      - 3000:3000
    command: tail -f /dev/null

volumes:
  vendor:
